package com.opencode.android.util

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import com.opencode.android.data.model.ChatMessage
import com.opencode.android.data.model.MessageRole
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object MarkdownExporter {

    fun generateMarkdown(sessionTitle: String, messages: List<ChatMessage>): String {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        val exportTime = dateFormat.format(Date())

        val sb = StringBuilder()
        sb.append("# 📝 OpenCode 会话记录: ").append(sessionTitle).append("\n\n")
        sb.append("> 导出时间: ").append(exportTime).append(" | 消息总数: ").append(messages.size).append(" 条\n\n")
        sb.append("---\n\n")

        if (messages.isEmpty()) {
            sb.append("*(当前会话暂无消息记录)*\n")
            return sb.toString()
        }

        for (msg in messages) {
            val msgTime = dateFormat.format(Date(msg.timestamp))
            when (msg.role) {
                MessageRole.USER -> {
                    sb.append("### 👤 用户指令 [").append(msgTime).append("]\n\n")
                    sb.append(msg.content.trim()).append("\n\n")
                }
                MessageRole.ASSISTANT -> {
                    sb.append("### 🤖 OpenCode 输出 [").append(msgTime).append("]\n\n")
                    sb.append(msg.content.trim()).append("\n\n")

                    if (msg.toolEvents.isNotEmpty()) {
                        sb.append("#### 🛠️ 工具调用与执行轨迹\n\n")
                        sb.append("```bash\n")
                        msg.toolEvents.forEach { event ->
                            sb.append(event).append("\n")
                        }
                        sb.append("```\n\n")
                    }
                }
                MessageRole.SYSTEM -> {
                    val icon = if (msg.isError) "❌ 异常告警" else "⚙️ 系统通知"
                    sb.append("### ").append(icon).append(" [").append(msgTime).append("]\n\n")
                    sb.append("> ").append(msg.content.trim()).append("\n\n")
                }
            }
            sb.append("---\n\n")
        }

        sb.append("*Generated by OpenCode Android Remote Client*\n")
        return sb.toString()
    }

    fun shareMarkdown(context: Context, title: String, markdownContent: String) {
        try {
            val sendIntent = Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_TEXT, markdownContent)
                putExtra(Intent.EXTRA_SUBJECT, "OpenCode 会话导出: $title")
                type = "text/plain"
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
            val shareIntent = Intent.createChooser(sendIntent, "分享会话 Markdown 到...").apply {
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
            context.startActivity(shareIntent)
        } catch (e: Exception) {
            Toast.makeText(context, "无法唤起系统分享: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun copyToClipboard(context: Context, text: String) {
        try {
            val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager
            val clip = ClipData.newPlainText("OpenCode Markdown", text)
            clipboard?.setPrimaryClip(clip)
            Toast.makeText(context, "已将完整 Markdown 复制到剪贴板", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, "复制失败: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }
}
