package com.opencode.android.util

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import com.opencode.android.data.model.ChatMessage
import com.opencode.android.data.model.MessageRole
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object MarkdownExporter {

    fun generateMarkdown(context: Context, sessionTitle: String, messages: List<ChatMessage>): String {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        val exportTime = dateFormat.format(Date())

        val sb = StringBuilder()
        sb.append(context.getString(R.string.export_001)).append(sessionTitle).append("\n\n")
        sb.append(context.getString(R.string.export_002)).append(exportTime).append(context.getString(R.string.export_003)).append(messages.size).append(context.getString(R.string.export_004))
        sb.append("---\n\n")

        if (messages.isEmpty()) {
            sb.append(context.getString(R.string.export_005))
            return sb.toString()
        }

        for (msg in messages) {
            val msgTime = dateFormat.format(Date(msg.timestamp))
            when (msg.role) {
                MessageRole.USER -> {
                    sb.append(context.getString(R.string.export_006)).append(msgTime).append("]\n\n")
                    sb.append(msg.content.trim()).append("\n\n")
                }
                MessageRole.ASSISTANT -> {
                    sb.append(context.getString(R.string.export_007)).append(msgTime).append("]\n\n")
                    sb.append(msg.content.trim()).append("\n\n")

                    if (msg.toolEvents.isNotEmpty()) {
                        sb.append(context.getString(R.string.export_008))
                        sb.append("```bash\n")
                        msg.toolEvents.forEach { event ->
                            sb.append(event).append("\n")
                        }
                        sb.append("```\n\n")
                    }
                }
                MessageRole.SYSTEM -> {
                    val icon = if (msg.isError) context.getString(R.string.export_009) else context.getString(R.string.export_010)
                    sb.append("### ").append(icon).append(" [").append(msgTime).append("]\n\n")
                    sb.append("> ").append(msg.content.trim()).append("\n\n")
                }
            }
            sb.append("---\n\n")
        }

        sb.append("*Generated by OpenCode Android Remote Client*\n")
        return sb.toString()
    }

    fun shareMarkdown(context: Context, title: String, markdownContent: String) {
        try {
            val sendIntent = Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_TEXT, markdownContent)
                putExtra(Intent.EXTRA_SUBJECT, context.getString(R.string.export_011, title))
                type = "text/plain"
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
            val shareIntent = Intent.createChooser(sendIntent, context.getString(R.string.export_012)).apply {
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
            context.startActivity(shareIntent)
        } catch (e: Exception) {
            Toast.makeText(context, context.getString(R.string.export_013, e.message), Toast.LENGTH_SHORT).show()
        }
    }

    fun copyToClipboard(context: Context, text: String) {
        try {
            val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager
            val clip = ClipData.newPlainText("OpenCode Markdown", text)
            clipboard?.setPrimaryClip(clip)
            Toast.makeText(context, context.getString(R.string.export_014), Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, context.getString(R.string.export_015, e.message), Toast.LENGTH_SHORT).show()
        }
    }
}
